INSERT INTO public.rescue_partners (name, city, state, url) VALUES
('Texas Critter Crusaders', 'Taylor', 'TX', 'https://texascrittercrusaders.com/'),
('Caring Hearts 4 Paws', 'Toledo', 'WA', 'https://caringhearts4paws.org/'),
('Furry Friends Humane', 'Jupiter', 'FL', 'https://ffhumane.org/'),
('San Francisco SPCA', 'San Francisco', 'CA', 'https://www.sfspca.org/'),
('Heaven Can Wait Rescue', 'Congers', 'NY', 'https://heavencanwaitlv.org/'),
('Ho-Bo Care Boxer Rescue', 'Denver', 'CO', 'https://www.hobocare.org/'),
('Annenberg Pet Space', 'Playa Vista', 'CA', 'https://annenbergpetspace.org/'),
('Safe Animal Shelter of Orange County', 'Orange', 'FL', 'https://www.safeanimalshelter.com/'),
('Reagan and Rowan''s Rescue', 'Illinois City', 'IL', 'https://reaganandrowansrescue.com/'),
('Pawsitive Change', 'Athens', 'GA', 'https://pawsitive-change.org/'),
('Lodi Animal Services Foundation', 'Lodi', 'CA', 'https://www.thelasf.org/'),
('El Dorado County German Shepherd Rescue', 'Shingle Springs', 'CA', 'https://www.grcgla.org/'),
('Golden Retriever Club Of Greater Los Angelos', 'Los Angeles', 'CA', 'https://www.grcgla.org/'),
('Whitman County Humane Society', 'Pullman', 'WA', 'https://www.whitmanpets.org/'),
('Forget Me Not Animal Rescue', 'Joilet', 'IL', 'https://forgetmenotrescue.com/'),
('Bakersfield SPCA', 'Bakersfield', 'CA', 'https://bakersfieldspca.org/'),
('Better Together Pet Resource Center', 'Niagara Falls', 'NY', 'https://www.bettertogetherpetresourcecenter.org/'),
('The Animal Pad', 'San Diego', 'CA', 'https://theanimalpad.org/'),
('Relay For Rescue Inc.', 'Longmont', 'CO', 'http://relayforrescue.com/'),
('Hard Luck Animal Welfare Advocates', 'Sacramento', 'CA', 'https://www.hardluckawa.org/'),
('Triad Golden Retriever Rescue', 'Greensboro', 'NC', 'https://tgrr.org/'),
('PAALS', 'Columbia', 'SC', 'http://paals.org'),
('It''s a Pittie Rescue', 'Morris', 'IL', 'http://rescueapittie.org/'),
('New York Bully Crew', 'East Patchogue', 'NY', 'https://www.nybullycrew.org/'),
('Footbridge Foundation', 'San Antonio', 'TX', 'https://www.footbridgefoundation.org/'),
('Forever Loved Pet Sanctuary', 'Scottsdale', 'AZ', 'https://www.foreverlovedpets.org/'),
('Humane Society of Indianapolis', 'Carmel', 'IN', 'https://indyhumane.org/'),
('Athens Area Humane Society', 'Athens', 'GA', 'https://athenshumanesociety.org/'),
('Beagle Rescue Education and Welfare', 'Manasses', 'VA', 'https://brewbeagles.org/'),
('Last Hope Animal Rescue', 'Wantagh', 'NY', 'https://lasthopeanimalrescue.org/'),
('TJO Animals', 'Springfield', 'MA', 'https://www.tjofoundation.org/'),
('Hunter''s Village Rescue', 'Orlando', 'FL', 'https://huntersvillagerescue.rescuegroups.org/index.php'),
('San Antonio Humane Society', 'San Antonio', 'TX', 'https://sahumane.org/'),
('Oklahoma German Shepherd Rescue', 'Inola', 'OK', 'https://oklahomagsr.org/'),
('Florida Bulldog Rescue', 'Davenport', 'FL', 'https://www.flbulldogrescue.com/'),
('Althea Canines', 'Orangevale', 'CA', 'http://altheacanines.org'),
('Animal Protective Foundation of Schenectady', 'Glenville', 'NY', 'http://www.animalprotective.org/'),
('The Foster House', 'Charolette', 'NC', 'https://www.thefosterdoghouse.org/'),
('Out of the Pits, Inc.', 'Albany', 'NY', 'https://outofthepits.org/'),
('A.D.O.P.T. Pet Shelter', 'Naperville', 'IL', 'https://www.adoptpetshelter.org/'),
('GELA Foundation', 'Anderson', 'SC', 'https://www.gelafoundation.org/'),
('Supporting Our Needle Noses', 'New Castle', 'CO', 'https://www.sonns.org/'),
('Santa Barbara Animal Care Foundation', 'Santa Barbara', 'CA', 'https://www.sbcanimalcare.org/'),
('Pet Project Foundation', 'San Clemente', 'CA', 'https://petprojectfoundation.org/'),
('Iowa Humane alliance', 'Cedar Rapids', 'IA', 'https://iowahumanealliance.org/'),
('A Pathway to Hope', 'Haledon', 'NJ', 'http://www.apathwaytohope.org/'),
('Rocky Hills Farm', 'Pineville', 'MO', 'https://www.rhfrescue.com/'),
('Lake Oconee Humane Society', 'Greensboro', 'GA', 'https://lohspets.org/'),
('Bully Project Rescue', 'Lakeland', 'FL', 'https://bullyprojectrescue.org/'),
('The Grest Pyrenees Club of Western Pennsylvania', 'Pittsbourgh', 'PA', 'https://www.swpapyr.org/index.html'),
('Waggin Tales Rescue Foundation', 'Yountville', 'CA', 'https://www.waggintrailsrescue.com/'),
('The Rise Rescue Alliance', 'Port Angeles', 'WA', 'https://riserescue.org/'),
('Hardeman Adoptable Animals', 'Bolivar', 'TN', 'https://www.hardemanadoptableanimals.org/'),
('Shelter to Soldier', 'Oceanside', 'CA', 'https://specialtydogtraining.com/shelter-to-soldier-/'),
('Greyhounds In Motion', 'Winter Park', 'FL', 'https://rescuedogwines.com/event/foster-housewarming-party'),
('International Association of Canine Professionals', 'Chicago', 'Il', 'https://rescuedogwines.com/event/international-association-of-canine-professionals-annual-education-conference'),
('Street Paws', 'Locust Grove', 'GA', 'https://rescuedogwines.com/event/a-day-of-gratitude'),
('The Humane Society of Delaware County', 'Delaware', 'OH', 'https://rescuedogwines.com/event/furball-wine-dine-and-whiskers'),
('Daisy''s Legacy', 'Alington', 'VA', 'https://daisyslegacy.org/'),
('Rocket Dog Rescue', 'Oakland', 'CA', 'https://www.rocketdogrescue.org/'),
('Helen Woodward Animal Center', 'Rancho Sante Fe', 'CA', 'https://animalcenter.org/spring-fling-gala/'),
('Big Bones Canine Rescue', 'Fort Collins', 'CO', 'https://www.bigbonescaninerescue.com/'),
('Everyday Heroes Dog Rescue, Inc.', 'Waldwick', 'NJ', 'https://everydayheroesdogr.wixsite.com/everydayheroes'),
('PALS (Pets A Lone Sanctuary)', 'Old Monroe', 'MO', 'https://www.pals-pets.org/home'),
('Pleasant Hearts Pet Food Pantry', 'Grand Rapids', 'MI', 'https://www.pleasantheartspetfoodpantry.org/'),
('Golden Retriever Club of Greater Los Angeles Rescue', 'Los Angeles', 'CA', 'https://www.grcglarescue.org/'),
('Lucky Dog Animal Rescue', 'Washington', 'DC', 'https://www.luckydoganimalrescue.org/'),
('Dog Star Rescue', 'Bloomfield', 'Connecticut', ''),
('11th Hour Animal Rescue', 'Flanders', 'NJ', 'https://www.ehrdogs.org/'),
('Best Friends Animal Society', '', '', ''),
('Helen Woodward Animal Center', 'San Diego', 'CA', ''),
('Pups Without Borders', 'Van Nuys', 'CA', ''),
('Animal Rescue Foundation (ARF)', 'Walnut Creek', 'CA', ''),
('Barkee LaRoux''s House of Love', 'Palm Springs', 'CA', ''),
('Bubbles Dog Rescue', 'Santa Monica', 'CA', ''),
('Butte Humane Society', 'Chico', 'CA', ''),
('FACE Foundation', 'San Diego', 'CA', ''),
('Friends of Front Street Animal Shelter', 'Sacramento', 'CA', ''),
('Frosted Faces Foundation', 'Ramona', 'CA', ''),
('Helen Sanders Cat Protection and Welfare Society (Cat Paws)', 'Seal Beach', 'CA', ''),
('Humane Society of Truckee-Tahoe', 'Truckee', 'CA', ''),
('Humane Society of Sonoma County', 'Santa Rosa', 'CA', ''),
('NorCal Boxer Rescue', 'Davis', 'CA', ''),
('NorCal GSP Rescue', 'Menlo Park', 'CA', ''),
('Mary S. Roberts Adoption Center', 'Riverside', 'CA', ''),
('Placer SPCA', 'Roseville', 'CA', ''),
('Priceless Pets', 'Chino Hlls', 'CA', ''),
('Friends of the Palm Springs Animal Shelter', 'Palm Springs', 'CA', ''),
('RedRover', 'Sacramento', 'CA', ''),
('Siskiyou Humane Society', 'Mount Shasta', 'CA', ''),
('Stand Up For Pits Foundation', 'West Hollywood', 'CA', ''),
('Teaching Everyone Animals Matter (TEAM)', 'Sacramento', 'CA', ''),
('The Rescue Train', 'Los Angeles', 'CA', ''),
('True Love Rescue', 'Lodi', 'CA', ''),
('Friends of the Alameda Animal Shelter (FAAS)', 'Alameda', 'CA', ''),
('BirchBark Foundation', 'Santa Cruz', 'CA', ''),
('Cat Tales Rescue', 'Vacaville', 'CA', ''),
('Golden Gate Basset Rescue', 'Petaluma', 'CA', ''),
('Haven Humane Society', 'Anderson', 'CA', ''),
('Humane Society of Silicon Valley', 'Milpitas', 'CA', ''),
('Little Angels Project', 'Agoura Hills', 'CA', ''),
('LapCats', 'Sacramento', 'CA', ''),
('Marin Humane', 'Novato', 'CA', ''),
('Northern California Sled Dog Rescue (NorSled)', 'Walnut Creek', 'CA', ''),
('People Assisting Lodi Shelter (PALS)', 'Lodi', 'CA', ''),
('Passion for Pitties', 'Chula Vista', 'CA', ''),
('Paws to Party', 'Sacramento', 'CA', ''),
('Paw Works', 'Camarillo', 'CA', ''),
('Peace of Mind Dog Rescue', 'Pacific Grove', 'CA', ''),
('Pets in Need/u>', 'Redwood City', 'CA', ''),
('Pets Lifeline', 'Sonoma', 'CA', ''),
('Pug Nation of Los Angeles', 'Los Angeles', 'CA', ''),
('South County Tail Waggers', 'Gilroy', 'CA', ''),
('San Diego Humane Society', 'San Diego', 'CA', ''),
('Sacramento SPCA', 'Sacramento', 'CA', ''),
('Waggin'' Trails Rescue Foundation', 'Napa', 'CA', ''),
('Wags & Walks', 'Los Angeles', 'CA', ''),
('Better World Rescue', 'Tracy', 'CA', ''),
('Brunos Foundation', 'Lincoln', 'CA', ''),
('Carousel Ranch', 'Agua Dulce', 'CA', ''),
('Fosters & Paws', 'Sacramento', 'CA', ''),
('Friends of the Sonoma County Animal Shelter', 'Cloverdale', 'CA', ''),
('Humane Society of Tuolumne County', 'Pomona', 'CA', ''),
('Humane Society of Pomona Valley, Inc.', 'Jamestown', 'CA', ''),
('Ruger''s Rescue', 'San Diego', 'CA', ''),
('Santa Cruz SPCA', 'Aptos', 'CA', ''),
('Mile High Weimaraner Rescue', 'Denver', 'CO', ''),
('Golden Retriever Freedom Rescue', 'Denver', 'CO', ''),
('French Bulldog Rescue Network', 'West Hartford', 'CT', ''),
('Buddies thru Bullies', 'Plantation', 'FL', ''),
('Danny & Don''s Rescue', 'Ocala', 'FL', ''),
('Mutty Paws Rescue', 'West Palm Beach', 'FL', ''),
('Polo''s Refuge', 'Tallahassee', 'FL', ''),
('Saving with Soul', 'Crestview', 'FL', ''),
('St. Francis Society Animal Rescue', 'Tampa', 'FL', ''),
('Humane Society of Marion County', 'Ocala', 'FL', ''),
('Bark Back Benefit', 'Lake Worth Beach', 'FL', ''),
('Florida English Bulldog Rescue', 'Odessa', 'FL', ''),
('Lucky Puppy Rescue', 'Bonifay', 'FL', ''),
('Little Bear Sanctuary', 'Punta Gorda', 'FL', ''),
('Polk County Bully Project', 'Lakeland', 'FL', ''),
('Tampa Bay Strays', 'Tampa', 'FL', ''),
('Bosley''s Place', 'Smyrna', 'GA', ''),
('Atlanta Humane Society', 'Atlanta', 'GA', ''),
('Georgia English Bull Dog Rescue', 'Winder', 'GA', ''),
('Hearts ''n Homes Dog Rescue', 'Sharpsburg', 'GA', ''),
('Humane Society of Morgan County', 'Madison', 'GA', ''),
('Planned PEThood of Georgia', 'Duluth', 'GA', ''),
('Street Paws', 'McDonough', 'GA', ''),
('That''s What Friends Are For', 'Augusta', 'GA', ''),
('Charles Smithgall Humane Society', 'Sautee Nacoochee', 'GA', ''),
('Dog Networking Agents Inc', 'Evans', 'GA', ''),
('Oconee Regional Humane Society', 'Greensboro', 'GA', ''),
('PAWS Atlanta', 'Atlanta', 'GA', ''),
('Renegade Paws Rescue', 'Savannah', 'GA', ''),
('Habitat for Hounds', 'Macon', 'GA', ''),
('Iowa Humane Alliance', 'Marion', 'IA', ''),
('The Anti-Cruelty Society', 'Chicago', 'IL', ''),
('Chicago French Bulldog Rescue', 'Chicago', 'IL', ''),
('Naperville Area Humane Society', 'Naperville', 'IL', ''),
('It''s a Pittie Rescue', 'Kankakee', 'IL', ''),
('It Takes A Village', 'Evansville', 'IN', ''),
('Lakeshore PAWS', 'Valparaiso', 'IN', ''),
('Silver Snout Senior Dog Rescue', 'Indianapolis', 'IN', ''),
('Hoosier Bulldog Rescue', 'Indianapolis', 'IN', ''),
('Take Paws Rescue', 'New Orleans', 'LA', ''),
('I Heart Dogs Rescue and Animal Haven', 'Warren', 'MI', ''),
('Minnesota Boxer Rescue', 'Woodbury', 'MN', ''),
('Five Acres Animal Shelter', 'St. Charles', 'MO', ''),
('Adoption First Animal Rescue', 'Jacksonville', 'NC', ''),
('Arise Animal Rescue', 'Hubert', 'NC', ''),
('Catering to Cats & Dogs', 'Charlotte', 'NC', ''),
('Friends of Madison County Animals', 'Marshall', 'NC', ''),
('New Hampshire Humane Society', 'Laconia', 'NH', ''),
('New Rescue Haven Foundation', 'Saddle Brook', 'NJ', ''),
('Pet Network Humane Society', 'Incline Village', 'NV', ''),
('A Path For Paws', 'Las Vegas', 'NV', ''),
('NYC Second Chance Rescue', 'Long Island City', 'NY', ''),
('Hope For Cleo Animal Rescue', 'Smithtown', 'NY', ''),
('Muddy Paws Rescue', 'New York', 'NY', ''),
('Ridge''s Rescue', 'Rochester', 'NY', ''),
('Silver Hearts Sanctuary', 'Centereach', 'NY', ''),
('Humane Society of Greater Dayton', 'Dayton', 'OH', ''),
('Three Pits and a Lady', 'Stoutsville', 'OH', ''),
('Homeward Bound Pet Sanctuary', 'Cleveland', 'OH', ''),
('Lake Humane Society', 'Mentor', 'OH', ''),
('Humane Pennsylvania', 'Lancaster', 'PA', ''),
('Doberman Pinscher Rescue of PA', 'Oxford', 'PA', ''),
('Paws Across Pittsburgh', 'Pittsburgh', 'PA', ''),
('Cindy Lou''s Sanctuary', 'Moncks Corner', 'SC', ''),
('G.E.L.A. Foundation', 'Anderson', 'SC', ''),
('New Leash on Life', 'Lebanon', 'TN', ''),
('Big Fluffy Dog', 'LaVergne', 'TN', ''),
('Fox Valley Humane Association', 'Arlington', 'VA', ''),
('Lucky Dog Animal Rescue', 'Arlington', 'VA', ''),
('MustLuvBoxers Rescue', 'Stanwood', 'WA', ''),
('PACK (People For Animal Care and Kindness)', 'Gig Harbor', 'WA', ''),
('Streetdog Foundation', 'Memphis', 'TN', ''),
('Fox Valley Humane Association', 'Appleton', 'WI', ''),
('Southside SPCA', 'Meherrin', 'VA', ''),
('Pack Gives', 'Gig Harbor', 'WA', 'https://www.packgives.org/'),
('TriCounty Animal Rescue', 'Boca Raton', 'FL', 'https://www.tricountyanimalrescue.com/'),
('Humane Society Silicon Valley', 'San Jose', 'CA', 'https://www.hssv.org/'),
('Pets In Need', 'Palo Alto', 'CA', ''),
('Saving Paws Animal Rescue of Kentucky', 'Owensboro', 'KY', 'https://rescuedogwines.com/event/saving-paws-animal-rescue-of-kentucky'),
('Misfit Mutts Dog Rescue', 'Green Bay', 'WI', 'https://misfitmuttsdogrescue.com/'),
('Almost Home Animal Rescue', '', '', 'https://www.almosthomear.com/'),
('Gone Rogue Girls Rescue Inc', 'Long Branch', 'NJ', 'https://www.goneroguegirlsrescueinc.com/');